import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Aplus Navigators",
  description: "Generated by JOMAFA",
};

export default function RootLayout({
  children,
}:{
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="items-center justify-center">
        <Navbar />
        <main className={`${geistSans.variable} ${geistMono.variable} antialiased relative overflow-hidden`}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
